# =========================================================================
# === STAGE 1: COMPILACIÓN ===
# =========================================================================

# Usamos una imagen que ya incluye Maven 3 y JDK 21 (Temurin)
FROM maven:3.9.6-eclipse-temurin-21-alpine AS builder

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de configuración de Maven (pom.xml) y el código fuente
COPY pom.xml .
COPY src ./src

# Compila el proyecto con Maven y salta las pruebas
# Usamos un cache para las dependencias, lo que acelera los builds futuros
RUN --mount=type=cache,target=/root/.m2 mvn clean package -DskipTests

# =========================================================================
# === STAGE 2: IMAGEN FINAL PARA EJECUCIÓN ===
# =========================================================================

# Usamos una imagen de JRE 21 (más pequeña que el JDK) para ejecutar la aplicación
FROM eclipse-temurin:21-jre-alpine

# Establece el directorio de trabajo dentro del contenedor final
WORKDIR /app

# Copia el archivo JAR compilado desde el stage 'builder'
COPY --from=builder /app/target/projectapp-0.0.1-SNAPSHOT.jar app.jar

# Define el puerto por el que escuchará tu aplicación
EXPOSE 8080

# Comando para ejecutar la aplicación cuando el contenedor se inicie
ENTRYPOINT ["java", "-jar", "app.jar"]